baseURL = 'https://www.cloudfun.in'
languageCode = 'en-us'
title = 'Cloudfun blog'
theme = "aether"


[Params]
subtititle = "A place for my thoughts on cloud and DevOps" 
logo = "img/cloud-sun-logo-260nw-1035026638.jpg"

[Author]
website = "cloudfun.in"
email = "contact@cloudfun.in"
youtube = "cloudfun"